version: '3.7'

services:
  clickhouse-master:
    container_name: clickhouse-master
    restart: unless-stopped
    image: clickhouse/clickhouse-server
    user: root
    depends_on:
      - caddy
    env_file:
        - clickhouse.env
    ports:
      - "9000:9000"
      - "9440:9440"
      - "9363:9363"
    networks:
      clickhouse-net:
    volumes:
      - /data/clickhouse-master:/var/lib/clickhouse
      - /data/clickhouse-master-logs:/var/log/clickhouse-server
      - /root/clickhouse.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - /etc/clickhouse-server/config.xml:/etc/clickhouse-server/config.d/config.xml
      - caddy_data:/etc/clickhouse-server/ssl:ro

  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy:2.4.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - clickhouse-net

  supabase-grafana:
    container_name: grafana
    restart: unless-stopped
    image: docker.io/capgo/supabase-grafana
    ports:
      - 8081:8080
    env_file:
        - grafana.env
    volumes:
      - grafana_data:/data

networks:
  clickhouse-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  caddy_data:
  caddy_config:
  grafana_data:
